image: frodenas/couchdb

script:
  # workaround for cache, see https://github.com/drone/drone/issues/147
  - mkdir -p /tmp/npm
  - npm config set cache /tmp/npm --global

  # actual tests
  - npm install --silent
  - npm test

notify:
  email:
    recipients:
      - katzki@ubilabs.net

cache:
  - /tmp/npm
